repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff-format
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/RobertCraigie/pyright-pre-commit
    rev: v1.1.358
    hooks:
      - id: basedpyright
        additional_dependencies: ["basedpyright"]
        stages: [pre-push]
