[project]
name = "lineart"
version = "0.0.0"
requires-python = ">=3.8,<3.12"

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E","F","W","I","UP","D","B","C90"]

[tool.mypy]
python_version = "3.11"
strict = true

[tool.pylint.'MAIN']
# Beispiel: Naming/Gewichtung etc.

[tool.vulture]
min_confidence = 80
exclude = ["tests/*"]

[tool.deptry]
# Beispiel: Regeln/Ignores hier steuern
