[project]
name = "lineart"
version = "0.0.0"
requires-python = ">=3.8,<3.12"
dependencies = [
    "torch",
    "diffusers",
    "controlnet-aux",
    "pillow",
    "opencv-python",
    "scikit-image",
    "numpy",
    "requests",
]

[project.optional-dependencies]
gui = ["tkinterdnd2"]
svg = ["vtracer"]

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E","F","W","I","UP","D","B","C90"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true
exclude = ["tests/"]

[tool.pylint.'MAIN']
# Beispiel: Naming/Gewichtung etc.

[tool.vulture]
min_confidence = 80
exclude = ["tests/*"]

[tool.deptry]
per_rule_ignores = { "DEP002" = ["vtracer"] }

[tool.deptry.package_module_name_map]
"opencv-python" = ["cv2"]
"pillow" = ["PIL"]
"scikit-image" = ["skimage"]
